// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkpTLXRWnWd_2mOHZbXTX_WVvUCQ2UfRQ',
    appId: '1:443786785898:web:a11b78168e718ff7064613',
    messagingSenderId: '443786785898',
    projectId: 'chat-app-fbe6b',
    authDomain: 'chat-app-fbe6b.firebaseapp.com',
    storageBucket: 'chat-app-fbe6b.appspot.com',
    measurementId: 'G-CH9M71YDMM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqEW6zFBDqOcxNcgI10N_6iAbQdFBnles',
    appId: '1:443786785898:android:c450866d59e36682064613',
    messagingSenderId: '443786785898',
    projectId: 'chat-app-fbe6b',
    storageBucket: 'chat-app-fbe6b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRoZPDbanRqklMvMc3w4pqYJleh6TTaFI',
    appId: '1:443786785898:ios:ac84dd7caf6599d1064613',
    messagingSenderId: '443786785898',
    projectId: 'chat-app-fbe6b',
    storageBucket: 'chat-app-fbe6b.appspot.com',
    iosClientId: '443786785898-km9drltc2iaj9vssms2unur0e0lqnmgn.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );
}
